name: CI

on:
  push:
    branches: [main, beta]
  pull_request:
    branches: [main, beta]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.2'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint and format
        run: npm run fix
      
      - name: Build
        run: npm run build
      
      - name: Test
        run: npm test
      
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            dist
            *.tsbuildinfo
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-